# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b0e9ce2d4a71370f06fe6e507feab2cce7d25a20c9b16278e5efe9df829a27b70fb290b8254e1e4e16799589bf4d648a6dd975edf3c96e59a0bbb8aaedff12a

test:
  secret_key_base: 423d60eb54cd50429067a0f77cb56f9f6d0e20f5db4b07007a67f1278c109ff0ad1961a2095b4d8141f99b17ebeff3e17d5e2ab412b798dc1e3e63508f81999a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
